from __future__ import annotations

import random
from dataclasses import dataclass
from datetime import date, timedelta
from pathlib import Path

from fpdf import FPDF


@dataclass
class Txn:
    day: date
    description: str
    debit: float | None
    credit: float | None
    balance: float


FAKE_DESCRIPTIONS = [
    "POS PURCHASE EXAMPLE MART",
    "ACH PAYROLL DEPOSIT",
    "ONLINE TRANSFER",
    "ATM WITHDRAWAL",
    "UTILITY PAYMENT",
    "CARD 4532 RETAIL",
    "INTEREST CREDIT",
    "FEE MONTHLY SERVICE",
]


def _money(n: float) -> str:
    return f"{n:,.2f}"


def build_transactions(pages: int, rows: int, seed: int) -> list[Txn]:
    rng = random.Random(seed)
    start = date(2026, 1, 2)
    balance = rng.uniform(8000, 20000)
    out: list[Txn] = []
    for i in range(pages * rows):
        day = start + timedelta(days=i % 28)
        desc = rng.choice(FAKE_DESCRIPTIONS)
        if rng.random() < 0.55:
            debit = round(rng.uniform(5, 420), 2)
            credit = None
            balance -= debit
        else:
            credit = round(rng.uniform(20, 1500), 2)
            debit = None
            balance += credit
        out.append(Txn(day, desc, debit, credit, round(balance, 2)))
    return out


def write_pdf(
    path: Path,
    *,
    pages: int = 1,
    rows: int = 10,
    seed: int = 42,
    bank_name: str = "Example National Bank",
) -> Path:
    txns = build_transactions(pages, rows, seed)
    pdf = FPDF(orientation="P", unit="mm", format="A4")
    pdf.set_auto_page_break(auto=True, margin=15)

    for page_idx in range(pages):
        pdf.add_page()
        pdf.set_font("Helvetica", "B", 14)
        pdf.cell(0, 8, bank_name, new_x="LMARGIN", new_y="NEXT")
        pdf.set_font("Helvetica", "B", 11)
        pdf.set_text_color(180, 0, 0)
        pdf.cell(0, 7, "SYNTHETIC / NOT A REAL STATEMENT", new_x="LMARGIN", new_y="NEXT")
        pdf.set_text_color(0, 0, 0)
        pdf.set_font("Helvetica", size=10)
        pdf.cell(0, 6, "Account name: Alex Example", new_x="LMARGIN", new_y="NEXT")
        pdf.cell(0, 6, "Account number: ****-****-1234", new_x="LMARGIN", new_y="NEXT")
        pdf.cell(
            0,
            6,
            f"Statement seed: {seed}  |  Page {page_idx + 1}/{pages}",
            new_x="LMARGIN",
            new_y="NEXT",
        )
        pdf.ln(3)

        pdf.set_font("Helvetica", "B", 9)
        for label, width in [
            ("Date", 22),
            ("Description", 85),
            ("Debit", 25),
            ("Credit", 25),
            ("Balance", 28),
        ]:
            pdf.cell(width, 7, label, border=1)
        pdf.ln()

        pdf.set_font("Helvetica", size=8)
        chunk = txns[page_idx * rows : (page_idx + 1) * rows]
        for txn in chunk:
            pdf.cell(22, 6, txn.day.isoformat(), border=1)
            pdf.cell(85, 6, txn.description[:42], border=1)
            pdf.cell(25, 6, _money(txn.debit) if txn.debit is not None else "", border=1)
            pdf.cell(25, 6, _money(txn.credit) if txn.credit is not None else "", border=1)
            pdf.cell(28, 6, _money(txn.balance), border=1)
            pdf.ln()

        pdf.set_y(-20)
        pdf.set_font("Helvetica", "I", 8)
        pdf.set_text_color(120, 120, 120)
        pdf.cell(0, 5, "Generated by statement-synth for OCR testing only.", new_x="LMARGIN", new_y="NEXT")

    path = Path(path)
    path.parent.mkdir(parents=True, exist_ok=True)
    pdf.output(str(path))
    return path
